# See https://reuse.software/spec-3.2/#reusetoml for specification
version = 1
SPDX-PackageName = "Controlplane"
SPDX-PackageSupplier = "Deutsche Telekom AG <opensource@telekom.de>"
SPDX-PackageDownloadLocation = "https://github.com/telekom/controlplane"

[[annotations]]
path = "**/docs/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2025 Deutsche Telekom IT GmbH"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["LICENSE", "CODEOWNERS"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2025 Deutsche Telekom IT GmbH"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [".pre-commit-config.yaml", "REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2025 Deutsche Telekom IT GmbH"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/testdata/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2025 Deutsche Telekom IT GmbH"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".github/dependabot.yml"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2025 Deutsche Telekom IT GmbH"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "CHANGELOG.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2025 Deutsche Telekom IT GmbH"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/helm/**/*.yaml"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2025 Deutsche Telekom IT GmbH"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/__snapshots__/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2025 Deutsche Telekom IT GmbH"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/mocks/data/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2025 Deutsche Telekom IT GmbH"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".mcp.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2025 Deutsche Telekom IT GmbH"
SPDX-License-Identifier = "CC0-1.0"
