# SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  name: routes.gateway.cp.ei.telekom.de
spec:
  group: gateway.cp.ei.telekom.de
  names:
    kind: Route
    listKind: RouteList
    plural: routes
    singular: route
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Route is the Schema for the routes API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: RouteSpec defines the desired state of Route
            properties:
              downstreams:
                items:
                  properties:
                    host:
                      type: string
                    issuerUrl:
                      type: string
                    path:
                      type: string
                    port:
                      type: integer
                  required:
                  - host
                  - path
                  - port
                  type: object
                type: array
              passThrough:
                default: false
                description: PassThrough is a flag to pass through the request to
                  the upstream without authentication
                type: boolean
              realm:
                description: |-
                  ObjectRef is a reference to a Kubernetes object
                  It is similar to types.NamespacedName but has the required json tags for serialization
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                  uid:
                    description: |-
                      UID is a type that holds unique ID values, including UUIDs.  Because we
                      don't ONLY use UUIDs, this is an alias to string.  Being a type captures
                      intent and helps make sure that UIDs and names do not get conflated.
                    type: string
                required:
                - name
                - namespace
                type: object
              upstreams:
                items:
                  properties:
                    host:
                      type: string
                    issuerUrl:
                      type: string
                    path:
                      type: string
                    port:
                      type: integer
                    scheme:
                      type: string
                    security:
                      description: Security is the security configuration for the
                        upstream
                      properties:
                        h2m:
                          description: H2M defines human-to-machine authentication
                            configuration
                          type: object
                        m2m:
                          description: M2M defines machine-to-machine authentication
                            configuration
                          properties:
                            basic:
                              description: Basic defines basic authentication configuration
                              properties:
                                password:
                                  description: Password for basic authentication
                                  minLength: 1
                                  type: string
                                username:
                                  description: Username for basic authentication
                                  minLength: 1
                                  type: string
                              required:
                              - password
                              - username
                              type: object
                            client:
                              description: Client defines client credentials for OAuth2
                                for LMS from the **internal** IDP
                              properties:
                                clientId:
                                  description: ClientId identifies the client for
                                    OAuth2 client credentials flow
                                  minLength: 1
                                  type: string
                                clientSecret:
                                  description: ClientSecret is the secret associated
                                    with the client ID
                                  minLength: 1
                                  type: string
                                scopes:
                                  description: Scopes defines the OAuth2 scopes to
                                    request in the token
                                  items:
                                    type: string
                                  type: array
                              required:
                              - clientId
                              - clientSecret
                              type: object
                            externalIDP:
                              description: ExternalIDPConfig defines external identity
                                provider configuration
                              properties:
                                client:
                                  description: Client defines client credentials for
                                    OAuth2 for external IDP
                                  properties:
                                    clientId:
                                      description: ClientId identifies the client
                                        for OAuth2 client credentials flow
                                      minLength: 1
                                      type: string
                                    clientSecret:
                                      description: ClientSecret is the secret associated
                                        with the client ID
                                      minLength: 1
                                      type: string
                                    scopes:
                                      description: Scopes defines the OAuth2 scopes
                                        to request in the token
                                      items:
                                        type: string
                                      type: array
                                  required:
                                  - clientId
                                  - clientSecret
                                  type: object
                                grantType:
                                  description: GrantType is the grant type for the
                                    external IDP authentication
                                  enum:
                                  - client_credentials
                                  - authorization_code
                                  - password
                                  type: string
                                tokenEndpoint:
                                  description: TokenEndpoint is the URL for the OAuth2
                                    token endpoint
                                  format: uri
                                  type: string
                                tokenRequest:
                                  description: TokenRequest is the type of token request,
                                    "body" or "header"
                                  enum:
                                  - body
                                  - header
                                  type: string
                              required:
                              - tokenEndpoint
                              type: object
                            scopes:
                              description: Scopes defines additional OAuth2 scopes
                                that are added to the LMS token
                              items:
                                type: string
                              maxItems: 10
                              type: array
                          type: object
                          x-kubernetes-validations:
                          - message: ExternalIDP and basic authentication cannot be
                              used together
                            rule: 'self == null || (has(self.externalIDP) ? (!has(self.basic))
                              : true)'
                      type: object
                      x-kubernetes-validations:
                      - message: Only one of m2m or h2m authentication can be provided
                          (XOR relationship)
                        rule: self == null || has(self.m2m) != has(self.h2m)
                  required:
                  - host
                  - path
                  - port
                  - scheme
                  type: object
                type: array
            required:
            - downstreams
            - passThrough
            - realm
            - upstreams
            type: object
          status:
            description: RouteStatus defines the observed state of Route
            properties:
              conditions:
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              consumers:
                items:
                  type: string
                type: array
              properties:
                additionalProperties:
                  type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
